[package]
name = "deep-spider"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown = "0.16.1"
html2md = "0.2.15"
regex = "1.12.3"
scraper = "0.25.0"
spider = { version = "2.45.19", features = ["regex"] }
url = "2.5.8"

